apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: k8s-intro
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: training/webapp:latest
        ports:
        - containerPort: 5000
        # add resource usage limitation
        resources:
          requests:
            cpu: "0.1"
            memory: "200Mi"
          limits:
            cpu: "0.2"
            memory: "300Mi"

---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: k8s-intro
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service-lb
  namespace: k8s-intro
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: k8s-intro
spec:
  ingressClassName: nginx
  rules:
  - host: "helloworld.k8s-intra.pp.ua"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-world-service
            port:
              number: 5000
  tls:
  - hosts:
     - helloworld.k8s-intra.pp.ua
    secretName: testsecret-tls
