apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: k8s-intro
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: training/webapp:latest
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: k8s-intro
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 5000
  type: ClusterIP